SELECT 'CREATE DATABASE pokecenter'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'pokecenter')\gexec

CREATE TABLE CLIENT (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);


CREATE ENUM TRANSACTION_TYPE AS ENUM ('CREDIT', 'DEBIT');
CREATE TABLE TRANSACTIONS (
  id SERIAL PRIMARY KEY,
  amount DECIMAL(10,2) NOT NULL,
  type TRANSACTION_TYPE NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  FOREIGN KEY (user_id) REFERENCES CLIENT(id)
);

CREATE TABLE BALANCE (
  id SERIAL PRIMARY KEY,
  amount DECIMAL(10,2) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  FOREIGN KEY (user_id) REFERENCES CLIENT(id)
);

INSERT INTO CLIENT (name, phone) VALUES ('John Doe', '123456789');
INSERT INTO CLIENT (name, phone) VALUES ('Jane Doe', '987654321');
INSERT INTO CLIENT (name, phone) VALUES ('John Smith', '123456789');
INSERT INTO CLIENT (name, phone) VALUES ('Jane Smith', '987654321');
INSERT INTO TRANSACTIONS (amount, type, user_id) VALUES (100.00, 'CREDIT', 1);
INSERT INTO TRANSACTIONS (amount, type, user_id) VALUES (50.00, 'DEBIT', 1);
INSERT INTO TRANSACTIONS (amount, type, user_id) VALUES (100.00, 'CREDIT', 2);
INSERT INTO TRANSACTIONS (amount, type, user_id) VALUES (50.00, 'DEBIT', 2);
INSERT INTO TRANSACTIONS (amount, type, user_id) VALUES (100.00, 'CREDIT', 3);
INSERT INTO TRANSACTIONS (amount, type, user_id) VALUES (50.00, 'DEBIT', 3);
INSERT INTO TRANSACTIONS (amount, type, user_id) VALUES (100.00, 'CREDIT', 4);
INSERT INTO TRANSACTIONS (amount, type, user_id) VALUES (50.00, 'DEBIT', 4);
INSERT INTO BALANCE (amount, user_id) VALUES (50.00, 1);
INSERT INTO BALANCE (amount, user_id) VALUES (50.00, 2);
INSERT INTO BALANCE (amount, user_id) VALUES (50.00, 3);
INSERT INTO BALANCE (amount, user_id) VALUES (50.00, 4);